### ISSUE TITLE
Outdated dspp-keras pip package

### ISSUE THREAD

**Issue by ktamiola** [PeptoneInc/dspp-keras#4]
I have updated `dspp-keras` with 
```
pip instal dspp-keras --upgrade
```
All looks good. However, the example produces:

```
Using TensorFlow backend.
Downloading data from https://github.com/PeptoneInc/dspp-data/blob/master/database.pkl?raw=true
Traceback (most recent call last):
  File "dspp_cnn.py", line 130, in <module>
    X, Y = dspp.load_data()
  File "/usr/local/lib/python2.7/dist-packages/dsppkeras/datasets/dspp.py", line 15, in load_data
    path = get_file(path, origin='https://github.com/PeptoneInc/dspp-data/blob/master/database.pkl?raw=true')
  File "/usr/local/lib/python2.7/dist-packages/dsppkeras/utils/data_utils.py", line 203, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/PeptoneInc/dspp-data/blob/master/database.pkl?raw=true: None -- Not Found
```

**Comment by jandom** [comment]
Many thanks for reporting and the excellent instructions on how to reproduce – this should be resolved now with the release of v0.0.3 of the package
