### ISSUE TITLE
h5py dependency

### ISSUE THREAD

**Issue by ktamiola** [PeptoneInc/dspp-keras#9]
We may need to consider adding `h5py` dependency to `pip` package.

```
Traceback (most recent call last):
  File "dspp_cnn.py", line 148, in <module>
    model.save_weights("model.h5")
  File "/home/kamil/.local/lib/python2.7/site-packages/keras/models.py", line 723, in save_weights
    raise ImportError('`save_weights` requires h5py.')
ImportError: `save_weights` requires h5py.
```

**Comment by ktamiola** [comment]
Merci!
